name: Workflow
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9' 
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - run: sam build
      # working-directory: cloud-resume-challenge
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      # working-directory: cloud-resume-challenge

  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: cloud-resume-website-abishek-siva
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: cloud-resume-challenge/resume-site